extern void drive_forward();
extern void drive_backward();
extern void arc_left();
extern void arc_right();
extern void reverse_arc_left(int speed);
extern void reverse_arc_right(int speed);
extern void sharp_left();
extern void sharp_left_var(int speed);
extern void sharp_right();
extern void sharp_right_var(int speed);
extern void motors_off();
extern void pump_on();
extern void pump_off();
extern void initialize_motors();
