
#define OUTPUT_PIN_E_LEFT 14
#define OUTPUT_PIN_A_LEFT 15
#define OUTPUT_PIN_B_LEFT 18
#define OUTPUT_PIN_E_RIGHT 25
#define OUTPUT_PIN_A_RIGHT 8
#define OUTPUT_PIN_B_RIGHT 7
#define OUTPUT_PIN_E_PUMP 10
#define OUTPUT_PIN_A_PUMP 9
#define OUTPUT_PIN_B_PUMP 11

#define ULTRA_SONIC_OUTPUT_PIN 23
#define ULTRA_SONIC_INPUT_PIN 24

#define MICRO_SEC_IN_SEC 1000000

